### ISSUE TITLE
Primus Plugins not included?

### ISSUE THREAD

**Issue by zawnk** [kkemple/primus-webpack-plugin#9]
I use primus-emit and when I use this webpack-plugin, client-side the emit plugin does not seem to be included. When I generate it manually with primus.library() and primus.save() and copy it in the right folder, primus-emit is included and works without issues client-side. Is there something I have to watch out for or is this a bug?

Thanks :)

Edit: Forgot to mention that I include both in the webpack config

```
new PrimusWebpackPlugin({
      filename: 'primus-client.[hash].js',
      minify: true,
      primusOptions: {
        transformer: 'uws',
        plugin: {
          'emit': require('primus-emit'),
          'rooms': require('primus-rooms')
        }
      }
    })
```

And installed them client-side with --save-dev

**Comment by newyork-anthonyng** [comment]
@zawnk Can you create a basic repository that shows the primus client-side library getting manually created correctly?

**Comment by zawnk** [comment]
@newyork-anthonyng Hey,

I don't have a repo on github sadly, but it's not much code. Server side:

Dependencies:

 "primus": "^7.1.1",
 "primus-emit": "^1.0.0",
 "primus-rooms": "^3.4.1",

And my websocket gets initialized / a client file gets generated with:

```js
 const server = require('http').createServer(app)
 const primus = new Primus(server, {
   transformer: 'uws'
 })
 primus.plugin('emit', require('primus-emit'))
 primus.plugin('rooms', require('primus-rooms'))
 server.listen(config.webSocketPort)
 console.log(`Websocket Server started on port ${config.webSocketPort}`)
 if (process.env.NODE_ENV === 'production') {
   primus.library()
   primus.save(process.cwd() + '/primusclient.js')
   console.log('Client file generated to: ', process.cwd())
 }
```

That's also pretty much what's described on the primus repo. This way the primusclient.js gets generated and the size is much bigger than the Webpack plugin's client js (~25kb vs 65kb). Client-side I just:

```js
var Primus = window.Primus

var primus = Primus.connect(process.env.WS_URL, {
  strategy: 'online, disconnect'
})
```

And the webpack plugin config I've already posted :)

**Comment by newyork-anthonyng** [comment]
I just built the Primus client manually, and with webpack. The resulting files were identical in size. 

@zawnk Can you create a basic repository that recreates the issue you're seeing? Otherwise, I don't think I can help.

**Comment by newyork-anthonyng** [comment]
Hey,

I responded back to the issue.

I can't help unless you recreate the issue with the repository.

-Anthony

**Comment by zawnk** [comment]
Mhhh, I must've mixed out multiple environments.. I saw today my npm installs were not in package json. I tried it again from scratch and the file difference came from the minify :) Seems to work now!
